"""add_priority_to_billing_cases

Revision ID: 163008bdf9bb
Revises: 4eb0b674ff24
Create Date: 2026-07-03 04:49:38.777760
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '163008bdf9bb'
down_revision: Union[str, None] = '4eb0b674ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_cases', sa.Column('priority', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_billing_cases_priority'), 'billing_cases', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_cases_priority'), table_name='billing_cases')
    op.drop_column('billing_cases', 'priority')
    # ### end Alembic commands ###
