"""initial_schema

Revision ID: 50f5aa02ad50
Revises: 
Create Date: 2026-07-03 01:28:23.325252
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50f5aa02ad50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cases',
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_dob', sa.String(length=20), nullable=True),
    sa.Column('subscriber_id', sa.String(length=100), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('payer_phone', sa.String(length=20), nullable=True),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('service_date', sa.String(length=20), nullable=True),
    sa.Column('cpt_codes', sa.Text(), nullable=True),
    sa.Column('icd10_codes', sa.Text(), nullable=True),
    sa.Column('amount_billed', sa.Float(), nullable=True),
    sa.Column('denial_code', sa.String(length=50), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_cases_claim_number'), 'billing_cases', ['claim_number'], unique=False)
    op.create_index(op.f('ix_billing_cases_payer_name'), 'billing_cases', ['payer_name'], unique=False)
    op.create_index(op.f('ix_billing_cases_status'), 'billing_cases', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('call_jobs',
    sa.Column('billing_case_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_case_id'], ['billing_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_jobs_billing_case_id'), 'call_jobs', ['billing_case_id'], unique=False)
    op.create_index(op.f('ix_call_jobs_created_by'), 'call_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_call_jobs_status'), 'call_jobs', ['status'], unique=False)
    op.create_table('call_sessions',
    sa.Column('call_job_id', sa.String(length=36), nullable=False),
    sa.Column('twilio_call_sid', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('agent_phase', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('outcome_details', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_job_id'], ['call_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_call_sid')
    )
    op.create_index(op.f('ix_call_sessions_call_job_id'), 'call_sessions', ['call_job_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_status'), 'call_sessions', ['status'], unique=False)
    op.create_table('call_events',
    sa.Column('call_session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_session_id'), 'call_events', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_call_events_event_type'), 'call_events', ['event_type'], unique=False)
    op.create_table('conversation_memories',
    sa.Column('call_session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memories_call_session_id'), 'conversation_memories', ['call_session_id'], unique=False)
    op.create_table('human_handoffs',
    sa.Column('call_session_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('agent_phase', sa.String(length=50), nullable=True),
    sa.Column('confidence_at_handoff', sa.String(length=10), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_handoffs_call_session_id'), 'human_handoffs', ['call_session_id'], unique=False)
    op.create_table('tickets',
    sa.Column('call_session_id', sa.String(length=36), nullable=True),
    sa.Column('billing_case_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['billing_case_id'], ['billing_cases.id'], ),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_billing_case_id'), 'tickets', ['billing_case_id'], unique=False)
    op.create_index(op.f('ix_tickets_call_session_id'), 'tickets', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('transcripts',
    sa.Column('call_session_id', sa.String(length=36), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_call_session_id'), 'transcripts', ['call_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_call_session_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_call_session_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_billing_case_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_human_handoffs_call_session_id'), table_name='human_handoffs')
    op.drop_table('human_handoffs')
    op.drop_index(op.f('ix_conversation_memories_call_session_id'), table_name='conversation_memories')
    op.drop_table('conversation_memories')
    op.drop_index(op.f('ix_call_events_event_type'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_session_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_call_sessions_status'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_call_job_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_call_jobs_status'), table_name='call_jobs')
    op.drop_index(op.f('ix_call_jobs_created_by'), table_name='call_jobs')
    op.drop_index(op.f('ix_call_jobs_billing_case_id'), table_name='call_jobs')
    op.drop_table('call_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_billing_cases_status'), table_name='billing_cases')
    op.drop_index(op.f('ix_billing_cases_payer_name'), table_name='billing_cases')
    op.drop_index(op.f('ix_billing_cases_claim_number'), table_name='billing_cases')
    op.drop_table('billing_cases')
    # ### end Alembic commands ###
